[custom]

#规则集定义
ruleset=🤖 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Lan/Lan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.list
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
ruleset=📢 GoogleFCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
ruleset=🍀 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=💧 bing,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Bing/Bing.list
ruleset=💧 Copilot,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Copilot/Copilot.list
ruleset=🐬 OneDrive,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OneDrive/OneDrive.list
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list
ruleset=♻️ Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Speedtest/Speedtest.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Epic/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Origin/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Sony/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Steam/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Nintendo/Nintendo.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Blizzard/Blizzard.list
ruleset=🎥 Netflix,hhttps://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=🎞️ 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/DouYin/DouYin.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Download/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China.list
ruleset=🚫 屏蔽广告,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/AdGuard/Advertising/Advertising.txt
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL



#策略组定义
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🐸 手动切换`[]DIRECT`[]🕊️ 便宜节点`[]🕊️ 便宜节点2
#custom_proxy_group=♻️ 自动选择`url-test`(?=.*(B|D|E|H))(?!.*(D21|B13|E0|香港边缘|香港宽频|日本星链D5|日本宽频D4))`http://www.gstatic.com/generate_204`300,,50
#custom_proxy_group=♻️ 自动选择`url-test`(?=.*(B|D|E|H))(?!.*(香港|0\.01|0\.1|0\.2|0\.3|0\.4|0\.5|0\.6|2\.0|D21|B13|E0|D21|B13|E0|香港边缘|香港宽频|日本星链D5|日本宽频D4|GIA|澳门|菲律宾|2.0|4.0|6.0|10.0))`http://www.gstatic.com/generate_204`300,,50
#custom_proxy_group=♻️ 自动选择`url-test`(?!.*(香港|0\.01|0\.1|0\.2|0\.3|0\.4|0\.5|0\.6|2\.0|D21|B13|E0|日本星链D5|日本宽频D4|GIA|澳门|菲律宾))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动选择`url-test`(?!.*香港)(?!.*(0\.01|0\.1|0\.2|0\.3|0\.4|0\.5|0\.6|2\.0|4\.0|6\.0|10\.0|D21|B13|E0|日本星链D5|日本宽频D4|GIA|澳门|菲律宾))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🐸 手动切换`select`.*
custom_proxy_group=🕊️ 便宜节点`url-test`(?=.*(0\.01|0\.1|0\.2|0\.3|0\.4|0\.5|0\.6|0\.7|0\.8|0\.9))`http://www.gstatic.com/generate_204`300,,50
#custom_proxy_group=🕊️ 便宜节点`url-test`(?=.*(0.01|0.1|0.2|0.3|0.4|0.5|0.5倍|0.5x|0.6))`http://www.gstatic.com/generate_204`300,,50
#filter: '0\.01|0\.1|0\.2|0\.3|0\.4|0\.5|0\.6|0\.7|0\.8|0\.9'
custom_proxy_group=🕊️ 便宜节点2`url-test`(?=.*(0\.01|0\.1|0\.2|0\.3))`https://chatgpt.com/generate_204`300,,50
custom_proxy_group=🤖 AI专用`url-test`(?=.*AI)`https://chatgpt.com/generate_204`300,,50
custom_proxy_group=💸 超贵节点`url-test`(?=.*(GIA|日本星链D5|日本宽频D4|2.0|4.0|6.0|10.0))`https://chatgpt.com/generate_204`300,,50
#各项节点选择
custom_proxy_group=🤖 AI`select`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT`[]🕊️ 便宜节点`[]🕊️ 便宜节点2
custom_proxy_group=💧 bing`select`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT`[]🕊️ 便宜节点
custom_proxy_group=💧 Copilot`select`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT`[]🕊️ 便宜节点
custom_proxy_group=🐬 OneDrive`select`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT`[]🕊️ 便宜节点
custom_proxy_group=🪟 Microsoft`select`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT`[]🕊️ 便宜节点
custom_proxy_group=👨🏿‍💻 GitHub`select`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT`[]🕊️ 便宜节点
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🐸 手动切换`[]🚀 节点选择`[]🕊️ 便宜节点
custom_proxy_group=🎮 游戏平台`select`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT`[]🕊️ 便宜节点
custom_proxy_group=♻️ Speedtest`select`[]DIRECT`[]🐸 手动切换`[]🚀 节点选择`[]🕊️ 便宜节点
custom_proxy_group=🎵 TikTok`select`[]🚀 节点选择`[]🐸 手动切换`[]🕊️ 便宜节点
custom_proxy_group=📲 Telegram`select`[]🚀 节点选择`[]🐸 手动切换`[]🕊️ 便宜节点`[]🕊️ 便宜节点2
custom_proxy_group=🍀 Google`select`[]🚀 节点选择`[]🐸 手动切换`[]DIRECT`[]🕊️ 便宜节点
custom_proxy_group=📢 GoogleFCM`select`[]🚀 节点选择`[]🐸 手动切换`[]🕊️ 便宜节点
custom_proxy_group=📹 YouTube`select`[]🚀 节点选择`[]📹 YouTubeCN`[]📹 YouTubeHK`[]📹 YouTubeSG`[]📹 YouTubeUS`[]📹 YouTubeJP`[]DIRECT`[]🕊️ 便宜节点
custom_proxy_group=🎥 Netflix`select`[]🚀 节点选择`[]🎥 奈飞HK`[]🎥 奈飞US`[]🎥 奈飞SG`[]🕊️ 便宜节点
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🐸 手动切换`[]🕊️ 便宜节点
custom_proxy_group=🎞️ 国内媒体`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换`[]🕊️ 便宜节点
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]🐸 手动切换`[]🕊️ 便宜节点
custom_proxy_group=🚫 屏蔽广告`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🕊️ 便宜节点`[]🐸 手动切换
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]REJECT`[]🚀 节点选择`[]🐸 手动切换

#各项细分
##奈非
custom_proxy_group=🎥 奈飞HK`url-test`(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎥 奈飞US`url-test`(?=.*(美国|US|United|USA))`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎥 奈飞SG`url-test`(?=.*(新加坡|SG|Singapore|🇸🇬))`http://www.gstatic.com/generate_204`300,,50
#YouTube
custom_proxy_group=📹 YouTubeCN`url-test`(?=.*台湾)`https://www.youtube.com/generate_204`300,2,50
custom_proxy_group=📹 YouTubeHK`url-test`(?=.*香港)`https://www.youtube.com/generate_204`300,2,50
custom_proxy_group=📹 YouTubeSG`url-test`(?=.*新加坡)`https://www.youtube.com/generate_204`300,2,50
custom_proxy_group=📹 YouTubeUS`url-test`(?=.*(美国|US|United|USA))`https://www.youtube.com/generate_204`300,2,50
custom_proxy_group=📹 YouTubeJP`url-test`(?=.*日本)`https://www.youtube.com/generate_204`300,2,50
#样本
#custom_proxy_group=📹 YouTubeJP`url-test`(?=.*(D1|台|TW|Taiwan))^((?!Y|V).)*$`https://www.youtube.com/generate_204`300,2,50
#custom_proxy_group=📹 YouTubeCN`url-test`(?=.*台湾)`https://www.youtube.com/generate_204`300,2,50
#启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
